packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - '@firebase/util'
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - esbuild
  - prisma
  - protobufjs
  - sharp
